config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
  	#my part
  	#get :confirm_email
  	root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'

  get '/about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	before_create :confirmation_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs

  private
     def confirmation_token
         if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
         end
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.where(user_id: current_user)
	end

	def show
	end

	def new
		@doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'new'
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private

	    def find_doc
	    	@doc = Doc.find(params[:id])
	    end

	    def doc_params
	    	params.require(:doc).permit(:title, :content)
	    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  %br
  = f.input :content
  %br
  =f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Fix Doc!

  = render 'form'
  %br
  = link_to "Cancel", doc_path, class: "btn btn-danger"

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)

    - else
      %h2 Create Doc!
      %p Start Creating Documents and Organize your life!
      %button= link_to "Create Doc", new_doc_path 

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1= @doc.title
    %p= simple_format(@doc.content)
    
    .buttons
      = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
      =link_to "Trash it", doc_path(@doc), method: :delete, data: { confirm: "Are you Sure?" }, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title File_keeper
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Libre+Barcode+39+Text"
  = stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Special+Elite"
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  ="https://fonts.googleapis.com/css?family=Calligraffitti" 
  
%body
  %header
    .header_inner
      = link_to "All_files", root_path, id: "logo"
      
      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path, class: "btn btn-success"
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-success"

        - else
          = link_to "about", about_path, id: "logo"
          = link_to "log in", new_user_session_path, class: "btn btn-success"
  
  %p.notice= notice
  %p.alert= alert
  = yield

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.png" %>
	</div>

	<div id="content">
		<h1>Dear visitor</h1>
		<h3> find me:</h3>
        <%= link_to "Github", "https://github.com/xNos33", class: "btn btn-danger" %>
        
        <%= link_to "FB", "https://www.facebook.com/xnos.xnos", class: "btn btn-danger" %>
		<p>If you belong_to :pentesters "family" feel free to test your abilitys, but dont damage this Site because i use it for my Portfolio</p>
		<h2>permision granded!#@</h2>
	</div>
</div>

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 your_FILE_keeper
    %p Your life's work. Organized, Always.your_FILE_keeper is a "ruby on rails" web app dezigned for presentation porposes.Is an app that you can store your work!(files) and gain istant access on the web.It can hundle many users in a friendly and easy enviroment.Sign in so gain full access!@#
    = link_to "Enter", new_user_registration_path, class: "button"
    %br
    %hr
#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Lorem aliquip labore knausgaard affogato, subway tile gluten-free. Irony echo park vape reprehenderit whatever. Poke next level sunt succulents, esse subway tile snackwave. Echo park intelligentsia pok pok, 90's polaroid sint woke ennui edison bulb cold-pressed cardigan cliche paleo craft beer. Lyft swag pok pok taxidermy man braid coloring book selvage aliqua activated charcoal la croix knausgaard. Lorem kinfolk cold-pressed try-hard. Vape helvetica green juice swag iceland hell of ad vegan adipisicing crucifix enim mumblecore. Live-edge pok pok hell of, ethical skateboard cliche stumptown chia tumblr adipisicing normcore pug disrupt affogato. Hell of kitsch distillery, do unicorn tousled raclette hammock direct trade.

#botton_cta
  .wrapper
    %h2 Go Ahead!
    %br
    = link_to "Join Now", new_user_registration_path, class: "button"